before_install:
  - gem install cocoapods
install:
  - brew update && brew upgrade swiftlint
  - pod install
language: swift
osx_image: xcode11.6
xcode_workspace: Nonton.xcworkspace # path to your xcworkspace file
xcode_scheme: Nonton
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 8
script:
 - swiftlint
 - xcodebuild -workspace 'Nonton.xcworkspace' -scheme 'Nonton' -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 8'
